# CERA 2019 presentation: Python for Analyzing and Visualizing Education Data
#### 45-min presentation at CERA 2019 on using python for ananalyzing and visualizing education data. First half will illustrate a typical data analysis workflow and the second part will be sharing resources for further learning.

<details>
    <summary><strong>Goal</strong></summary>
    The goal of this notebook is to provide an example of a typical data analysis workflow.
    <ul>
        <li> measurable goals for this notebook </li>
        <li> Identify <i>variables of interest in dataset. </li>
        <li> Clean the dataset and create an analytical file.</li>
        <li> Create effective data visualizations illustrating some of the findings </li>
    </ul>
</details>

<details>
    <summary><strong>Context</strong></summary>
    We've downloaded raw data from <strong><i>IPEDS</i></strong> and are now in the process of creating an analytical mastefile.
</details>

***

Preparing your working environment:
1. `pandas`: data analysis library.
2. `zipfile`: let's you work with zipped files.
3. `pathlib`: allows you to create _filepath_ objects so you can navigate the file system regardless of the operating system (i.e. using forward slashes vs back slashes)
4. `tools`: is a python script in the same working directory. You can write your functions separately from this notebooks and **import** them as needed. This will keep your notebook clean.
5. `datetime`: to create a date stamp. more powerful version control systems like `git` would be better but at least _tagging_ your files with a date can help you keep different versions.

In [1]:
import pandas as pd
from zipfile import ZipFile
from pathlib import Path
from tools import tree
from datetime import datetime as dt
today = dt.today().strftime("%d-%b-%y")

today

'18-Nov-19'

In [2]:
RAW_DATA = Path("../data/raw/")
INTERIM_DATA = Path("../data/interim/")
PROCESSED_DATA = Path("../data/processed/")
EXTERNAL_DATA = Path("../data/external/")
FINAL_DATA = Path("../data/final/")

In [3]:
tree(RAW_DATA)

+ ..\data\raw
    + 11-18-2019---387.zip

# Reading in data

We can use `ZipFile` to manipulate our zipped raw data in this environment.

In [4]:
file = ZipFile(RAW_DATA / '11-18-2019---387.zip')

In [5]:
file.filelist

[<ZipInfo filename='Data_11-18-2019---387.csv' compress_type=deflate external_attr=0x20 file_size=66990 compress_size=17514>,
 <ZipInfo filename='ValueLabels_11-18-2019---387.csv' compress_type=deflate external_attr=0x20 file_size=2457 compress_size=521>]

There's two `csv` files in there, we'll read each of them into their own `DataFrame`. The `DataFrame` is the primary data structure in `pandas`.

> Pandas DataFrame is two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. Pandas DataFrame consists of three principal components, the data, rows, and columns. <br>
\- _GeeksforGeeks.org_

In [6]:
data = pd.read_csv(file.open("Data_11-18-2019---387.csv"))
labels = pd.read_csv(file.open("ValueLabels_11-18-2019---387.csv"))

In [7]:
data.head()

,UnitID,Institution Name,Sector of institution (HD2018),Level of institution (HD2018),Control of institution (HD2018),Degree-granting status (HD2018),Degree of urbanization (Urban-centric locale) (HD2018),Tribal college (HD2018),Historically Black College or University (HD2018),Graduation rate total cohort (DRVGR2017_RV),...,Graduation rate - Bachelor degree within 6 years Asian/Native Hawaiian/Pacific Islander (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Asian (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Native Hawaiian or Other Pacific Islander (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Black non-Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years White non-Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years two or more races (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Race/ethnicity unknown (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Nonresident alien (DRVGR2017_RV),Unnamed: 36
0,491464,ABC Adult School,7,3,1,2,21,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,493105,ABC Adult School - Cabrillo Lane,99,-3,-3,-3,21,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,485500,ABCO Technology,9,3,3,2,21,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,488031,Abraham Lincoln University,3,1,3,1,12,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,457271,Academy for Jewish Religion-California,2,1,2,1,11,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
labels

,VariableName,Value,ValueLabel
0,Sector of institution (HD2018),0,Administrative Unit
1,Sector of institution (HD2018),1,"Public, 4-year or above"
2,Sector of institution (HD2018),2,"Private not-for-profit, 4-year or above"
3,Sector of institution (HD2018),3,"Private for-profit, 4-year or above"
4,Sector of institution (HD2018),4,"Public, 2-year"
5,Sector of institution (HD2018),5,"Private not-for-profit, 2-year"
6,Sector of institution (HD2018),6,"Private for-profit, 2-year"
7,Sector of institution (HD2018),7,"Public, less-than 2-year"
8,Sector of institution (HD2018),8,"Private not-for-profit, less-than 2-year"
9,Sector of institution (HD2018),9,"Private for-profit, less-than 2-year"
10,Sector of institution (HD2018),99,Sector unknown (not active)
11,Level of institution (HD2018),1,Four or more years
12,Level of institution (HD2018),2,At least 2 but less than 4 years
13,Level of institution (HD2018),3,Less than 2 years (below associate)
14,Level of institution (HD2018),-3,{Not available}
15,Control of institution (HD2018),1,Public
16,Control of institution (HD2018),2,Private not-for-profit
17,Control of institution (HD2018),3,Private for-profit
18,Control of institution (HD2018),-3,{Not available}
19,Degree-granting status (HD2018),1,Degree-granting
20,Degree-granting status (HD2018),2,"Nondegree-granting, primarily postsecondary"
21,Degree-granting status (HD2018),-3,{Not available}
22,Historically Black College or University (HD2018),2,No
23,Tribal college (HD2018),2,No
24,Degree of urbanization (Urban-centric locale) ...,11,City: Large
25,Degree of urbanization (Urban-centric locale) ...,12,City: Midsize
26,Degree of urbanization (Urban-centric locale) ...,13,City: Small
27,Degree of urbanization (Urban-centric locale) ...,21,Suburb: Large
28,Degree of urbanization (Urban-centric locale) ...,22,Suburb: Midsize
29,Degree of urbanization (Urban-centric locale) ...,23,Suburb: Small
30,Degree of urbanization (Urban-centric locale) ...,31,Town: Fringe
31,Degree of urbanization (Urban-centric locale) ...,32,Town: Distant
32,Degree of urbanization (Urban-centric locale) ...,33,Town: Remote
33,Degree of urbanization (Urban-centric locale) ...,41,Rural: Fringe
34,Degree of urbanization (Urban-centric locale) ...,42,Rural: Distant

# Exploring data

`Pandas` is designed for data analysis so it comes with lots of useful functions to explore your data

In [9]:
data.describe()

,UnitID,Sector of institution (HD2018),Level of institution (HD2018),Control of institution (HD2018),Degree-granting status (HD2018),Degree of urbanization (Urban-centric locale) (HD2018),Tribal college (HD2018),Historically Black College or University (HD2018),Graduation rate total cohort (DRVGR2017_RV),Graduation rate men (DRVGR2017_RV),...,Graduation rate - Bachelor degree within 6 years Asian/Native Hawaiian/Pacific Islander (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Asian (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Native Hawaiian or Other Pacific Islander (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Black non-Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years White non-Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years two or more races (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Race/ethnicity unknown (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Nonresident alien (DRVGR2017_RV),Unnamed: 36
count,663.000000,663.000000,663.000000,663.000000,663.000000,663.000000,663.0,663.0,510.000000,333.000000,...,118.000000,116.000000,84.000000,111.000000,124.000000,125.000000,103.000000,101.000000,102.000000,0.0
mean,276188.506787,5.600302,1.844646,2.138763,1.288084,16.514329,2.0,2.0,58.817647,48.264264,...,66.406780,66.456897,58.321429,49.144144,56.572581,61.208000,59.310680,59.257426,57.568627,NaN
std,168159.927854,9.418042,0.948045,0.976486,0.621828,7.000606,0.0,0.0,23.943944,24.547148,...,26.694613,26.637793,34.770906,29.279173,25.952168,23.797972,26.414505,27.073106,29.070931,NaN
min,108232.000000,0.000000,-3.000000,-3.000000,-3.000000,11.000000,2.0,2.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,117242.500000,2.000000,1.000000,1.000000,1.000000,11.000000,2.0,2.0,37.000000,27.000000,...,51.000000,50.750000,32.250000,30.000000,42.000000,46.000000,46.000000,42.000000,40.750000,NaN
50%,125499.000000,4.000000,2.000000,2.000000,1.000000,13.000000,2.0,2.0,64.000000,46.000000,...,70.000000,69.500000,57.000000,50.000000,56.500000,64.000000,60.000000,64.000000,58.500000,NaN
75%,454798.000000,9.000000,3.000000,3.000000,2.000000,21.000000,2.0,2.0,77.000000,66.000000,...,87.000000,88.250000,100.000000,71.000000,76.000000,79.000000,79.500000,80.000000,81.000000,NaN
max,493442.000000,99.000000,3.000000,3.000000,2.000000,42.000000,2.0,2.0,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 663 entries, 0 to 662
Data columns (total 37 columns):
UnitID                                                                                                        663 non-null int64
Institution Name                                                                                              663 non-null object
Sector of institution (HD2018)                                                                                663 non-null int64
Level of institution (HD2018)                                                                                 663 non-null int64
Control of institution (HD2018)                                                                               663 non-null int64
Degree-granting status (HD2018)                                                                               663 non-null int64
Degree of urbanization (Urban-centric locale) (HD2018)                                                        663 non-null int64
Tribal college (HD2018)                                                                                       663 non-null int64
Historically Black College or University (HD2018)                                                             663 non-null int64
Graduation rate  total cohort (DRVGR2017_RV)                                                                  510 non-null float64
Graduation rate  men (DRVGR2017_RV)                                                                           333 non-null float64
Graduation rate  women (DRVGR2017_RV)                                                                         335 non-null float64
Graduation rate  American Indian or Alaska Native (DRVGR2017_RV)                                              210 non-null float64
Graduation rate  Asian/Native Hawaiian/Other Pacific Islander (DRVGR2017_RV)                                  319 non-null float64
Graduation rate  Asian (DRVGR2017_RV)                                                                         313 non-null float64
Graduation rate  Native Hawaiian or Other Pacific Islander (DRVGR2017_RV)                                     240 non-null float64
Graduation rate  Black  non-Hispanic (DRVGR2017_RV)                                                           310 non-null float64
Graduation rate  Hispanic (DRVGR2017_RV)                                                                      325 non-null float64
Graduation rate  White  non-Hispanic (DRVGR2017_RV)                                                           327 non-null float64
Graduation rate  Nonresident alien (DRVGR2017_RV)                                                             222 non-null float64
Graduation rate  Race/ethnicity unknown (DRVGR2017_RV)                                                        267 non-null float64
Graduation rate  two or more races (DRVGR2017_RV)                                                             272 non-null float64
Graduation rate - Bachelor degree within 4 years  total (DRVGR2017_RV)                                        135 non-null float64
Graduation rate - Bachelor degree within 6 years  total (DRVGR2017_RV)                                        135 non-null float64
Graduation rate - Bachelor degree within 6 years  men (DRVGR2017_RV)                                          131 non-null float64
Graduation rate - Bachelor degree within 6 years  women (DRVGR2017_RV)                                        132 non-null float64
Graduation rate - Bachelor degree within 6 years  American Indian or Alaska Native (DRVGR2017_RV)             75 non-null float64
Graduation rate - Bachelor degree within 6 years  Asian/Native Hawaiian/Pacific Islander (DRVGR2017_RV)       118 non-null float64
Graduation rate - Bachelor degree within 6 years  Asian (DRVGR2017_RV)                                        116 non-null float64
Graduation rate - Bachelor degree within 6 years  Native Hawaiian or Other Pacific Islander (DRVGR2017_RV)    84 non-null float64
Graduation rate - Bachelor degree within 6 years  Black  non-Hispanic (DRVGR2017_RV)                          111 non-null float64
Graduation rate - Bachelor degree within 6 years  Hispanic (DRVGR2017_RV)                                     124 non-null float64
Graduation rate - Bachelor degree within 6 years  White  non-Hispanic (DRVGR2017_RV)                          125 non-null float64
Graduation rate - Bachelor degree within 6 years  two or more races (DRVGR2017_RV)                            103 non-null float64
Graduation rate - Bachelor degree within 6 years  Race/ethnicity unknown (DRVGR2017_RV)                       101 non-null float64
Graduation rate - Bachelor degree within 6 years  Nonresident alien (DRVGR2017_RV)                            102 non-null float64
Unnamed: 36                                                                                                   0 non-null float64
dtypes: float64(28), int64(8), object(1)
memory usage: 191.8+ KB

In [11]:
data.shape

(663, 37)

### Drop a column

It varies, but most of the time `pandas` methods and functions are _intuitive_. 

_I need to drop this column from a DataFrame so I "tell" the dataframe "drop" and pass the name of the column to it's "columns" argument._

In [12]:
data.drop(columns = 'Unnamed: 36')

,UnitID,Institution Name,Sector of institution (HD2018),Level of institution (HD2018),Control of institution (HD2018),Degree-granting status (HD2018),Degree of urbanization (Urban-centric locale) (HD2018),Tribal college (HD2018),Historically Black College or University (HD2018),Graduation rate total cohort (DRVGR2017_RV),...,Graduation rate - Bachelor degree within 6 years American Indian or Alaska Native (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Asian/Native Hawaiian/Pacific Islander (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Asian (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Native Hawaiian or Other Pacific Islander (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Black non-Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years White non-Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years two or more races (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Race/ethnicity unknown (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Nonresident alien (DRVGR2017_RV)
0,491464,ABC Adult School,7,3,1,2,21,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,493105,ABC Adult School - Cabrillo Lane,99,-3,-3,-3,21,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,485500,ABCO Technology,9,3,3,2,21,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,488031,Abraham Lincoln University,3,1,3,1,12,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,457271,Academy for Jewish Religion-California,2,1,2,1,11,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,126076,Yeshiva Ohr Elchonon Chabad West Coast Talmudi...,2,1,2,1,11,2,2,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,38.0,NaN,NaN,0.0
659,401250,Yo San University of Traditional Chinese Medicine,2,1,2,1,21,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,126100,Yosemite Community College District Office,0,1,1,1,12,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
661,126119,Yuba College,4,2,1,1,22,2,2,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662,486248,ZMS The Academy,9,3,3,2,11,2,2,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
data = data.drop(columns = 'Unnamed: 36')

# Adding labels to your data

We have a **data** `DataFrame` and a **value labels** `DataFrame` and what we want is to have those two in one.

In [14]:
value_labels = {}
for variable_name in labels['VariableName'].unique():
    # make a subset of the dataframe which contains only that variable
    working_df = labels[labels['VariableName'] == variable_name]
    # start a blank dictionary for each variable name
    value_labels[variable_name] = {}
    for (index, value_label) in working_df[['Value', 'ValueLabel']].iterrows():
        # iterate over each value - label and add them to the current dictionary
        value_labels[variable_name][value_label[0]] = value_label[1]

In [15]:
value_labels

{'Sector of institution (HD2018)': {0: 'Administrative Unit',
  1: 'Public, 4-year or above',
  2: 'Private not-for-profit, 4-year or above',
  3: 'Private for-profit, 4-year or above',
  4: 'Public, 2-year',
  5: 'Private not-for-profit, 2-year',
  6: 'Private for-profit, 2-year',
  7: 'Public, less-than 2-year',
  8: 'Private not-for-profit, less-than 2-year',
  9: 'Private for-profit, less-than 2-year',
  99: 'Sector unknown (not active)'},
 'Level of institution (HD2018)': {1: 'Four or more years',
  2: 'At least 2 but less than 4 years',
  3: 'Less than 2 years (below associate)',
  -3: '{Not available}'},
 'Control of institution (HD2018)': {1: 'Public',
  2: 'Private not-for-profit',
  3: 'Private for-profit',
  -3: '{Not available}'},
 'Degree-granting status (HD2018)': {1: 'Degree-granting',
  2: 'Nondegree-granting, primarily postsecondary',
  -3: '{Not available}'},
 'Historically Black College or University (HD2018)': {2: 'No'},
 'Tribal college (HD2018)': {2: 'No'},
 'Degree of urbanization (Urban-centric locale) (HD2018)': {11: 'City: Large',
  12: 'City: Midsize',
  13: 'City: Small',
  21: 'Suburb: Large',
  22: 'Suburb: Midsize',
  23: 'Suburb: Small',
  31: 'Town: Fringe',
  32: 'Town: Distant',
  33: 'Town: Remote',
  41: 'Rural: Fringe',
  42: 'Rural: Distant'}}

In [16]:
for key in value_labels.keys():
    data[key] = data[key].map(value_labels[key])

In [17]:
data.head()

,UnitID,Institution Name,Sector of institution (HD2018),Level of institution (HD2018),Control of institution (HD2018),Degree-granting status (HD2018),Degree of urbanization (Urban-centric locale) (HD2018),Tribal college (HD2018),Historically Black College or University (HD2018),Graduation rate total cohort (DRVGR2017_RV),...,Graduation rate - Bachelor degree within 6 years American Indian or Alaska Native (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Asian/Native Hawaiian/Pacific Islander (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Asian (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Native Hawaiian or Other Pacific Islander (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Black non-Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years White non-Hispanic (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years two or more races (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Race/ethnicity unknown (DRVGR2017_RV),Graduation rate - Bachelor degree within 6 years Nonresident alien (DRVGR2017_RV)
0,491464,ABC Adult School,"Public, less-than 2-year",Less than 2 years (below associate),Public,"Nondegree-granting, primarily postsecondary",Suburb: Large,No,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,493105,ABC Adult School - Cabrillo Lane,Sector unknown (not active),{Not available},{Not available},{Not available},Suburb: Large,No,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,485500,ABCO Technology,"Private for-profit, less-than 2-year",Less than 2 years (below associate),Private for-profit,"Nondegree-granting, primarily postsecondary",Suburb: Large,No,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,488031,Abraham Lincoln University,"Private for-profit, 4-year or above",Four or more years,Private for-profit,Degree-granting,City: Midsize,No,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,457271,Academy for Jewish Religion-California,"Private not-for-profit, 4-year or above",Four or more years,Private not-for-profit,Degree-granting,City: Large,No,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Filtering data

In [18]:
mask_sector = data['Sector of institution (HD2018)'] != 'Sector unknown (not active)'
mask_level = data['Level of institution (HD2018)'] != '{Not available}'
mask_control = data['Control of institution (HD2018)'] != '{Not available}'
mask_degree = data['Degree-granting status (HD2018)'] != '{Not available}'

In [19]:
data.shape

(663, 36)

In [20]:
data[mask_sector].shape

(657, 36)

In [21]:
data[mask_level].shape

(657, 36)

In [22]:
data[mask_control].shape

(657, 36)

In [23]:
data[mask_degree].shape

(657, 36)

In [24]:
data[mask_sector & mask_level & mask_control & mask_degree].shape

(657, 36)

In [25]:
data = data[mask_sector & mask_level & mask_control & mask_degree]

In [26]:
data.shape

(657, 36)

# Saving your work

In [27]:
data.to_csv(INTERIM_DATA / f'processed-data-{today}.csv', index = False)

In [32]:
data.to_excel(INTERIM_DATA / f'processed-data-{today}.xlsx', index = False)